<a href="https://colab.research.google.com/github/brianharnish/cs419/blob/master/labs/brian_bach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn import tree

In [9]:
chords = pd.read_csv('https://raw.githubusercontent.com/zacharski/ml-class/master/data/bach.zip')
chords.set_index('choral_ID', inplace=True)
chords = chords.drop('event_number', axis=1)
chords

             C  C#    D  D#    E    F  ...    A   A#   B bass meter chord_label
choral_ID                              ...
000106b_   YES  NO   NO  NO   NO  YES  ...  YES   NO  NO    F     3         F_M
000106b_   YES  NO   NO  NO  YES   NO  ...   NO   NO  NO    E     5         C_M
000106b_   YES  NO   NO  NO  YES   NO  ...   NO   NO  NO    E     2         C_M
000106b_   YES  NO   NO  NO   NO  YES  ...  YES   NO  NO    F     3         F_M
000106b_   YES  NO   NO  NO   NO  YES  ...  YES   NO  NO    F     2         F_M
...        ...  ..  ...  ..  ...  ...  ...  ...  ...  ..  ...   ...         ...
015505b_    NO  NO  YES  NO   NO   NO  ...   NO  YES  NO    G     4         G_m
015505b_    NO  NO  YES  NO   NO   NO  ...  YES   NO  NO    G     3         G_m
015505b_   YES  NO   NO  NO  YES   NO  ...   NO   NO  NO    C     5         C_M
015505b_   YES  NO   NO  NO  YES   NO  ...   NO  YES  NO    C     3         C_M
015505b_    NO  NO   NO  NO   NO  YES  ...  YES   NO  NO    F     4         F_M

[5665 rows x 15 columns]

In [10]:
one_hot = pd.get_dummies(chords['bass'], prefix=["bass"])
chords = chords.drop('bass', axis=1)
chords = chords.join(one_hot)
chords

             C  C#   D  D#  ... ['bass']_F ['bass']_F# ['bass']_G ['bass']_G#
choral_ID                   ...
000106b_   YES  NO  NO  NO  ...          1           0          0           0
000106b_   YES  NO  NO  NO  ...          0           0          0           0
000106b_   YES  NO  NO  NO  ...          0           0          0           0
000106b_   YES  NO  NO  NO  ...          1           0          0           0
000106b_   YES  NO  NO  NO  ...          1           0          0           0
...        ...  ..  ..  ..  ...        ...         ...        ...         ...
015505b_    NO  NO  NO  NO  ...          0           0          1           0
015505b_    NO  NO  NO  NO  ...          0           0          1           0
015505b_    NO  NO  NO  NO  ...          0           0          0           0
015505b_    NO  NO  NO  NO  ...          0           0          0           0
015505b_    NO  NO  NO  NO  ...          1           0          0           0

[599067 rows x 30 columns]

In [11]:
array = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
for i in array:
  chords[i] = chords[i].apply(lambda x: 1 if x == 'YES' else 0)
chords

           C  C#  D  D#  ...  ['bass']_F  ['bass']_F#  ['bass']_G  ['bass']_G#
choral_ID                ...
000106b_   1   0  0   0  ...           1            0           0            0
000106b_   1   0  0   0  ...           0            0           0            0
000106b_   1   0  0   0  ...           0            0           0            0
000106b_   1   0  0   0  ...           1            0           0            0
000106b_   1   0  0   0  ...           1            0           0            0
...       ..  .. ..  ..  ...         ...          ...         ...          ...
015505b_   0   0  0   0  ...           0            0           1            0
015505b_   0   0  0   0  ...           0            0           1            0
015505b_   0   0  0   0  ...           0            0           0            0
015505b_   0   0  0   0  ...           0            0           0            0
015505b_   0   0  0   0  ...           1            0           0            0

[599067 rows x 30 columns]

In [12]:
cFeatures = chords.drop('chord_label', axis=1)
cLabels = chords['chord_label']
chord_train_features, chord_test_features, chord_train_labels, chord_test_labels = train_test_split(cFeatures, cLabels, test_size = 0.2, random_state=42)
clf= tree.DecisionTreeClassifier(criterion= 'entropy')
clf.fit(chord_train_features, chord_train_labels)
cross_scores = cross_val_score(clf, chord_train_features, chord_train_labels, cv=10)

print(cross_scores)
print('Mean is {}'.format(cross_scores.mean()))

[0.81369194 0.8180737  0.81456829 0.81894627 0.81777778 0.81587898
 0.81385498 0.81658842 0.81771518 0.81717267]
Mean is 0.8164268203778164

In [14]:
from sklearn.metrics import accuracy_score
predictions = clf.predict(chord_test_features)
print(predictions)
accuracy_score = accuracy_score(chord_test_labels, predictions)
print(accuracy_score)
compare = pd.DataFrame(chord_test_labels)
compare['predicted'] = predictions
compare

['B_M' 'G_m' 'F#M' ... 'A_M' 'G_M' 'D_m7']
0.8153053900211995

          chord_label predicted
choral_ID
013906b_          B_M       B_M
000206b_          G_m       G_m
000408b_          F#M       F#M
015301b_         C#d7      C#d7
014007b_          BbM       BbM
...               ...       ...
000907b_          E_M       E_M
003006b_         A_M6      A_M6
002908ch          A_M       A_M
001907ch          C_M       G_M
000106b_         D_m7      D_m7

[119814 rows x 2 columns]